/*
 * |----------------JMat (Java Master)-------------------------------------|
 * |Setiap Manusia Yang Menata Hidupnya adalah Programmer                  |
 * |Hak Cipta Hanya Milik Allah SWT, Hamba-Nya Hanya Memanfaatkan.         |
 * |Manusia Tidak Bisa Mewujudkan Apa-apa, Manusia Hanya Bisa Merencanakan.| 
 * |----------------JMat (Java Master)-------------------------------------| 
 */
package san.jmat.panel.render;

import Program.Frame;
import com.stripbandunk.jglasspane.helper.GraphicHelper;
import com.stripbandunk.jglasspane.transition.image.CoverDownImageTransition;

import java.awt.CardLayout;

/**
 *
 * @author joker
 */
public class panelMenuBar extends javax.swing.JPanel {
    
    private Frame frame;

    /**
     * Creates new form panelMenuBar
     */
    public panelMenuBar() {
        initComponents();
    }
    
    public void setFrame(Frame frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFile = new san.jmat.button.render.buttonFile();
        buttonEditText1 = new san.jmat.button.render.buttonEditText();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnFile.setToolTipText("Menu File");
        btnFile.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnFile.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });
        add(btnFile);

        buttonEditText1.setText("Text");
        buttonEditText1.setToolTipText("Text");
        buttonEditText1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        buttonEditText1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        buttonEditText1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonEditText1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonEditText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditText1ActionPerformed(evt);
            }
        });
        add(buttonEditText1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        // TODO add your handling code here:
        CoverDownImageTransition transition = new CoverDownImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(frame.getPanelPivot(), frame.getGlassPane()));
        frame.getImageTransitionComponent1().setTransition(transition);
        frame.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout = (CardLayout) frame.getPanelPivot().getLayout();
        cardLayout.show(frame.getPanelPivot(), "itemFile");
    }//GEN-LAST:event_btnFileActionPerformed
    
    private void buttonEditText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditText1ActionPerformed
        // TODO add your handling code here:
        CoverDownImageTransition transition = new CoverDownImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(frame.getPanelPivot(), frame.getGlassPane()));
        frame.getImageTransitionComponent1().setTransition(transition);
        frame.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout = (CardLayout) frame.getPanelPivot().getLayout();
        cardLayout.show(frame.getPanelPivot(), "Menu Text");        
    }//GEN-LAST:event_buttonEditText1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private san.jmat.button.render.buttonFile btnFile;
    private san.jmat.button.render.buttonEditText buttonEditText1;
    // End of variables declaration//GEN-END:variables
}
