/*
 * |----------------JMat (Java Master)-------------------------------------|
 * |Setiap Manusia Yang Menata Hidupnya adalah Programmer                  |
 * |Hak Cipta Hanya Milik Allah SWT, Hamba-Nya Hanya Memanfaatkan.         |
 * |Manusia Tidak Bisa Mewujudkan Apa-apa, Manusia Hanya Bisa Merencanakan.| 
 * |----------------JMat (Java Master)-------------------------------------| 
 */
package san.jmat.panel.render;

import Program.Frame;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import san.jmat.combo.render.cFont;
import san.jmat.combo.render.cSize;
import san.jmat.kelas.CreateText;

/**
 *
 * @author joker
 */
public class subDialog extends javax.swing.JDialog {

    private panelMain pMain;
    private CreateText createText = new CreateText();
    private int text = -1;
    private DefaultComboBoxModel<String> comboBoxModelFont;
    private DefaultComboBoxModel comboBoxModelSize;

    /**
     * Creates new form subDialog
     */
    public subDialog(boolean modal, int create) {
        setModal(rootPaneCheckingEnabled);
        initComponents();
        pMain = new panelMain(panelViewText.getSize());
        panelViewText.add(pMain);
        //Jika Button 
        if (create != -1) {
            text = create;
            //setText
            createText.setText(Frame.packText.getText(text).getText());
            createText.setSizeFont(Frame.packText.getText(text).getSizeFont());
            createText.setColor(Frame.packText.getText(text).getColor());
            createText.setFontDefault(Frame.packText.getText(text).getFontDefault());
            pMain.setText(createText);
            textInput.setText(createText.getText());
        }
        comboBoxModelFont=new DefaultComboBoxModel<>();
        ComboFontRender();
        ComboSizeRender();

    }

    private void ComboFontRender() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(subDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                final Font[] allFonts;
                allFonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        for (Font font : allFonts) {
                            comboBoxModelFont.addElement(font.getName());
                        }
                        
                        comboFont.setModel(comboBoxModelFont);
                        comboFont.setRenderer(new cFont());
                    }
                });
            }
        }).start();
    }

    private void ComboSizeRender() {
    comboBoxModelSize=new DefaultComboBoxModel();
    for(int i=10;i<=120;i++){
        comboBoxModelSize.addElement(i);
    }
    comboUkuran.setModel(comboBoxModelSize);
    comboUkuran.setRenderer(new cSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground41 = new san.jmat.panel.render.panelBackground4();
        panelControl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textInput = new javax.swing.JTextArea();
        comboFont = new javax.swing.JComboBox();
        comboUkuran = new javax.swing.JComboBox();
        panelWarna = new javax.swing.JPanel();
        panelButton = new javax.swing.JPanel();
        buttonCancel1 = new san.jmat.button.render.buttonCancel();
        buttonOK1 = new san.jmat.button.render.buttonOK();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelViewText = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create or Update Text");

        panelControl.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Masukkan Text :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Font :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Size :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Color :");

        textInput.setBackground(new java.awt.Color(138, 235, 94));
        textInput.setColumns(20);
        textInput.setRows(5);
        textInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textInputKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textInput);

        comboFont.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFontActionPerformed(evt);
            }
        });

        comboUkuran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUkuranActionPerformed(evt);
            }
        });

        panelWarna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelWarnaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelWarnaLayout = new javax.swing.GroupLayout(panelWarna);
        panelWarna.setLayout(panelWarnaLayout);
        panelWarnaLayout.setHorizontalGroup(
            panelWarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        panelWarnaLayout.setVerticalGroup(
            panelWarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(panelWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFont, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelWarna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panelButton.setOpaque(false);

        buttonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancel1ActionPerformed(evt);
            }
        });
        panelButton.add(buttonCancel1);

        buttonOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOK1ActionPerformed(evt);
            }
        });
        panelButton.add(buttonOK1);

        panelViewText.setOpaque(false);

        javax.swing.GroupLayout panelViewTextLayout = new javax.swing.GroupLayout(panelViewText);
        panelViewText.setLayout(panelViewTextLayout);
        panelViewTextLayout.setHorizontalGroup(
            panelViewTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        panelViewTextLayout.setVerticalGroup(
            panelViewTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panelViewText);

        javax.swing.GroupLayout panelBackground41Layout = new javax.swing.GroupLayout(panelBackground41);
        panelBackground41.setLayout(panelBackground41Layout);
        panelBackground41Layout.setHorizontalGroup(
            panelBackground41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackground41Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackground41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panelBackground41Layout.setVerticalGroup(
            panelBackground41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackground41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelBackground41, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancel1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonCancel1ActionPerformed

    private void textInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textInputKeyTyped
        // TODO add your handling code here:
        String inputtanText = textInput.getText();
        if (inputtanText.length() > 0) {
            createText.setText(inputtanText);
            pMain.setText(createText);
            this.repaint();
        }
    }//GEN-LAST:event_textInputKeyTyped

    private void panelWarnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelWarnaMouseClicked
        // TODO add your handling code here:
        Color color;
        color = JColorChooser.showDialog(this, "Pilih Warna Untuk Text", Color.WHITE);
        panelWarna.setBackground(color);
        createText.setColor(color);
        this.repaint();
    }//GEN-LAST:event_panelWarnaMouseClicked

    private void comboFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFontActionPerformed
        // TODO add your handling code here:
        createText.setFontDefault(comboFont.getSelectedItem().toString());
        this.repaint();
    }//GEN-LAST:event_comboFontActionPerformed

    private void comboUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUkuranActionPerformed
        // TODO add your handling code here:
        createText.setSizeFont(Integer.parseInt(comboUkuran.getSelectedItem().toString()));
        this.repaint();
    }//GEN-LAST:event_comboUkuranActionPerformed

    private void buttonOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOK1ActionPerformed
        // TODO add your handling code here:
        if(text!=-1){
            Frame.packText.updateText(createText, text);
        }else{
            Frame.packText.setText(createText);
        }
        dispose();
    }//GEN-LAST:event_buttonOK1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private san.jmat.button.render.buttonCancel buttonCancel1;
    private san.jmat.button.render.buttonOK buttonOK1;
    private javax.swing.JComboBox comboFont;
    private javax.swing.JComboBox comboUkuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private san.jmat.panel.render.panelBackground4 panelBackground41;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelViewText;
    private javax.swing.JPanel panelWarna;
    private javax.swing.JTextArea textInput;
    // End of variables declaration//GEN-END:variables
}
